PythonVersion="3.13.11"
pythonBuildCommandsFile="/tmp/zipdeploy/extracted/oryx-build-commands.txt"
packagedir=".python_packages/lib/site-packages"
OperationId="878946df3812a37b"
SourceDirectoryInBuildContainer="/tmp/zipdeploy/extracted"
PlatformName="python"
CompressDestinationDir="false"
